#include "UtilsManaged.h"
#include "LexemeManaged.h"
#include "InflectionManaged.h"
#include "WordFormManaged.h"
#include "Singleton.h"

using namespace System;
//using namespace msclr::interop;
using namespace System::Runtime::InteropServices;
using namespace MainLibManaged;
using namespace std;

CWordFormManaged::CWordFormManaged(int64_t iHandle) : m_iHandle(iHandle)
{}

CWordFormManaged::~CWordFormManaged()
{
    m_iHandle = -1;
}

CWordForm* CWordFormManaged::pGetInstance()
{
    CWordForm* pWordForm = nullptr;
    auto rc = Singleton::pGetInstance()->eGetWordForm(m_iHandle, pWordForm);
    if (rc != H_NO_ERROR || nullptr == pWordForm)
    {
        throw gcnew Exception(L"Unable to retrieve word form instance.");
    }
    return pWordForm;
}

EM_ReturnCode CWordFormManaged::eGetInflection(CInflectionManaged^% inflection)
{
    CWordForm* pWordForm {nullptr};
    auto rc = Singleton::pGetInstance()->eGetWordForm(m_iHandle, pWordForm);
    if (rc != H_NO_ERROR || nullptr == pWordForm)
    {
        throw gcnew Exception(L"Unable to retrieve word form instance.");
    }

    auto pInflection = pWordForm->pInflection();
    if (rc != H_NO_ERROR || nullptr == pInflection)
    {
        throw gcnew Exception(L"Unable to retrieve inflection instance.");
    }

    auto iHandle = Singleton::pGetInstance()->iAddInflection(pInflection);
    inflection = gcnew CInflectionManaged(iHandle);

    return EM_ReturnCode::H_NO_ERROR;
}

//CLexemeManaged^ CWordFormManaged::Lexeme()
//{
//    if (nullptr == m_pWordForm)
//    {
//        throw gcnew Exception(L"WordForm object is NULL.");
//    }

//    return gcnew CLexemeManaged(m_pWordForm->spLexeme().get());
//}

//CWordForm* CWordFormManaged::pWordForm()
//{
//    return m_pWordForm;
//}

String^ CWordFormManaged::sWordForm()
{
    return gcnew String(pGetInstance()->sWordForm());
}

void CWordFormManaged::SetWordForm(String^ sWordForm)
{
    pGetInstance()->SetWordForm(sFromManagedString(sWordForm));
}

long long CWordFormManaged::llWordFormDbId()
{
    return pGetInstance()->llDbId();
}

String^ CWordFormManaged::sStem()
{
    return gcnew String(pGetInstance()->sStem());
}

void CWordFormManaged::SetStem(String^ sStem)
{
    pGetInstance()->SetStem(sFromManagedString(sStem));
}

__int64 CWordFormManaged::llLexemeId()
{
    return pGetInstance()->llLexemeId();
}

EM_PartOfSpeech CWordFormManaged::ePos()
{
    return (EM_PartOfSpeech)pGetInstance()->ePos();
}

void CWordFormManaged::SetPos(EM_PartOfSpeech ePos)
{
    pGetInstance()->SetPos((ET_PartOfSpeech)ePos);
}

EM_Case CWordFormManaged::eCase()
{
    return (EM_Case)pGetInstance()->eCase();
}

void CWordFormManaged::SetCase(EM_Case eCase)
{
    pGetInstance()->SetCase((ET_Case)eCase);
}

EM_Number CWordFormManaged::eNumber()
{
    return (EM_Number)pGetInstance()->eNumber();
}

void CWordFormManaged::SetNumber(EM_Number eNumber)
{
    pGetInstance()->SetNumber((ET_Number)eNumber);
}

EM_Subparadigm CWordFormManaged::eSubparadigm()
{
    return (EM_Subparadigm)pGetInstance()->eSubparadigm();
}

void CWordFormManaged::SetSubparadigm(EM_Subparadigm eSubparadigm)
{
    pGetInstance()->SetSubparadigm((ET_Subparadigm)eSubparadigm);
}

EM_Gender CWordFormManaged::eGender()
{
    return (EM_Gender)pGetInstance()->eGender();
}

void CWordFormManaged::SetGender(EM_Gender eGender)
{
    pGetInstance()->SetGender((ET_Gender)eGender);
}

EM_Person CWordFormManaged::ePerson()
{
    return (EM_Person)pGetInstance()->ePerson();
}

void CWordFormManaged::SetPerson(EM_Person ePerson)
{
    pGetInstance()->SetPerson((ET_Person)ePerson);
}

EM_Animacy CWordFormManaged::eAnimacy()
{
    return (EM_Animacy)pGetInstance()->eAnimacy();
}

void CWordFormManaged::SetAnimacy(EM_Animacy eAnimacy)
{
    pGetInstance()->SetAnimacy((ET_Animacy)eAnimacy);
}

EM_Reflexive CWordFormManaged::eReflexive()
{
    return (EM_Reflexive)pGetInstance()->eReflexive();
}

void CWordFormManaged::SetReflexivity(EM_Reflexive eReflexive)
{
    pGetInstance()->SetReflexivity((ET_Reflexivity)eReflexive);
}

EM_Aspect CWordFormManaged::eAspect()
{
    return (EM_Aspect)pGetInstance()->eAspect();
}

void CWordFormManaged::SetAspect(EM_Aspect eAspect)
{
    pGetInstance()->SetAspect((ET_Aspect)eAspect);
}

EM_Status CWordFormManaged::eStatus()
{
    return (EM_Status)pGetInstance()->eStatus();
}

void CWordFormManaged::SetStatus(EM_Status eStatus)
{
    pGetInstance()->SetStatus((ET_Status)eStatus);
}

bool CWordFormManaged::bIrregular()      // came from the DB as opposed to being generated by the app
{
    return pGetInstance()->bIrregular();
}

void CWordFormManaged::SetIrregular(bool bIrregular)
{
    pGetInstance()->SetIrregular(bIrregular);
}

String^ CWordFormManaged::sLeadComment()
{
    return gcnew String(pGetInstance()->sLeadComment());
}

void CWordFormManaged::SetLeadComment(String^ sLeadComment)
{
    pGetInstance()->SetLeadComment(sFromManagedString(sLeadComment));
}

String^ CWordFormManaged::sTrailingComment()
{
    return gcnew String(pGetInstance()->sTrailingComment());
}

void CWordFormManaged::SetTrailingComment(String^ sTrailingComment)
{
    pGetInstance()->SetTrailingComment(sFromManagedString(sTrailingComment));
}

bool CWordFormManaged::bIsEdited()
{
    return pGetInstance()->bIsEdited();
}

void CWordFormManaged::SetIsEdited(bool bIsEdited)
{
    return pGetInstance()->SetIsEdited(bIsEdited);
}

bool CWordFormManaged::bIsVariant()
{
    return pGetInstance()->bIsVariant();
}

void CWordFormManaged::SetIsVariant(bool bIsVariant)
{
    return pGetInstance()->SetIsVariant(bIsVariant);
}

EM_ReturnCode CWordFormManaged::eGetFirstStressPos(int% iPos, EM_StressType% eType)
{
    int cppiPos = -1;
    ET_StressType cppeType = ET_StressType::STRESS_TYPE_UNDEFINED;
    ET_ReturnCode eRet = pGetInstance()->eGetFirstStressPos(cppiPos, cppeType);
    if (H_NO_ERROR == eRet)
    {
        iPos = cppiPos;
        eType = (EM_StressType)cppeType;
    }
    return (EM_ReturnCode)eRet;
}

EM_ReturnCode CWordFormManaged::eGetNextStressPos(int% iPos, EM_StressType% eType)
{
    int cppiPos = -1;
    ET_StressType cppeType = ET_StressType::STRESS_TYPE_UNDEFINED;
    ET_ReturnCode eRet = pGetInstance()->eGetNextStressPos(cppiPos, cppeType);
    if (H_NO_ERROR == eRet)
    {
        iPos = cppiPos;
        eType = (EM_StressType)cppeType;
    }
    return (EM_ReturnCode)eRet;
}

EM_ReturnCode CWordFormManaged::eSetStressPositions(Collections::Generic::Dictionary<int, EM_StressType>^ dctStressPositions)
{
    Collections::Generic::Dictionary<int, EM_StressType>::Enumerator^ enumerator = dctStressPositions->GetEnumerator();
    map<int, ET_StressType> mapStressPositions;
    while (enumerator->MoveNext())
    {
        int iPos = enumerator->Current.Key;
        EM_StressType eType = enumerator->Current.Value;
        mapStressPositions[iPos] = (ET_StressType)eType;
    }

    ET_ReturnCode eRet = pGetInstance()->eSetStressPositions(mapStressPositions);
    return (EM_ReturnCode)eRet;
}

String^ CWordFormManaged::sGramHash()
{
    return gcnew String(pGetInstance()->sGramHash());
}

EM_ReturnCode CWordFormManaged::eInitFromHash(String^ sHash)
{
    return (EM_ReturnCode)pGetInstance()->eInitFromHash(sFromManagedString(sHash));
}

EM_ReturnCode CWordFormManaged::eSaveIrregularForm()
{
    return (EM_ReturnCode)pGetInstance()->eSaveIrregularForm();
}

//EM_ReturnCode CWordFormManaged::eSetIrregularStressPositions(Dictionary<int, EM_StressType>^ dictPositions)
//{
//    if (nullptr == m_pWordForm)
//    {
//        throw gcnew Exception(L"WordForm object is NULL.");
//    }

//    map<int, ET_StressType> mapPositions;
//    for each (KeyValuePair<int, EM_StressType> pairPosition in dictPositions)
//    {
//        mapPositions[pairPosition.Key] = (ET_StressType)pairPosition.Value;
//    }

//    auto eRet = m_pWordForm->eSaveIrregularStress(mapPositions);

//    return (EM_ReturnCode)eRet;
//}
